### ISSUE TITLE
Strange behavior of `include_files`?

### ISSUE THREAD

**Issue by utkarsh2102** [robotdana/fast_ignore#8]
Hi,

Thanks for your work on `fast_ignore`!
Whilst experimenting with it, I came across this:
```
irb(main):001:0> require 'fast_ignore'
=> true
irb(main):002:0> FastIgnore.new(include_files: 'README.md', relative: true).to_a
=> ["bin/console", "bin/time", "bin/ls_seconds", "bin/ls"]
```

I am not sure if it's expected? Or am I missing something obvious?

**Comment by robotdana** [comment]
include_files means read the README.md file as list of gitignore style patterns, it doesn't describe a pattern itself (that would be include_rules). Most of this file is invalid as a gitignore file, but it does have as an example a line containing only `#!:ruby`. This is then interpreted by the custom shebang pattern matching. 

I'll add this line to the documentation for ignore_files and include_files, do you think that will suffice?
`This is a list of files in the gitignore format to parse and match paths against, not a list of files to ignore/include`

**Comment by utkarsh2102** [comment]
Hi,

> include_files means read the README.md file as list of gitignore style patterns, it doesn't describe a pattern itself (that would be include_rules). Most of this file is invalid as a gitignore file, but it does have as an example a line containing only `#!:ruby`. This is then interpreted by the custom shebang pattern matching.

Ah, I see.

> I'll add this line to the documentation for ignore_files and include_files, do you think that will suffice?
> `This is a list of files in the gitignore format to parse and match paths against, not a list of files to ignore/include`

Yeah, I think this should do.
Maybe you could add "you might want to use `include_rules` instead" at the end of the above statement so that the people know that they want to use `include_rules` instead of `include_files` whenever they're in such a dilemma.

**Comment by robotdana** [comment]
yes that’s a great addition thank you
